### ISSUE TITLE
DamageHighlight implementation throws error in InspectionDetails

### ISSUE THREAD

**Issue by natsukiai** [monkvision/monkjs#293]
Hey @alexandre-em , this prop implementation throws an error, however I commented it just to keep working on the current feature.

_Originally posted by @BenHakimIlyass in https://github.com/monkvision/monkjs/pull/292#discussion_r898072899_

**Comment by BenHakimIlyass** [comment]
This throws the following error 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/50136109/173857709-c115323c-8a5b-4758-90b6-4e5d4af401c5.png">

And 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/50136109/173858102-9bbb3415-df7d-4dd7-91c1-1d9690b2567e.png">
