### ISSUE TITLE
Initiate work on video capture

### ISSUE THREAD

**Issue by natsukiai** [monkvision/monkjs#326]
![Image](https://user-images.githubusercontent.com/89044583/178449158-40ad4e7a-f4d9-4c30-a638-5fac267ae50c.png)

- [x] I can record a High quality video and cut it in ε seconds
- [ ] I can start a thread to process asynchronously the cut video
- [ ] I can export cleverly N frames from the video (depending on value of FPS)
- [ ] I can expose the frame for an embedded ML analyze
- [ ] I can treat result and filter them by compliance
- [x] I can compress and upload compliant pictures to the back-end
- [x] I can export sensors for compliant pictures
- [ ] I can store raw selected compliant pictures
- [ ] I can calculate a coverage score according to the compliance
- [ ] I can give advices according to the compliance
- [x] User can pause or stop recording
- [ ] I can end recording with a 100% coverage score

## Sensors consumption
To get all the needed info about the device sensors, we've created a hook `useSensors` that returns the following object:
```js
{
  accelerometer: {
    x: 0,
    y: 0,
    z: 0,
  },
  gyroscope: {
    x: 0,
    y: 0,
    z: 0,
  },
  magnometer: {
    x: 0,
    y: 0,
    z: 0,
  },
};
```

**Comment by BenHakimIlyass** [comment]
For the **N** frames to export what is the value **N**? Is it gonna be variable or fixed? If variable how shall we calculate it?
