### ISSUE TITLE
.WebP images are not animating on IOS devices

### ISSUE THREAD

**Issue by BenHakimIlyass** [monkvision/monkjs#89]
## Bug

When running the app on WEB or Android the animated .webP images are working pretty smooth, but not on IOS (no animation).

## Solution proposal

Since `.gif` files were working pretty smooth on IOS before, as a solution I propose bringing them back, compress them on [Gif Compressor](https://www.freeconvert.com/gif-compressor), and import them only for IOS.

**Comment by natsukiai** [comment]
Resolved by #91
