### ISSUE TITLE
Why not put the SIDEBAR_WIDTH in the style

### ISSUE THREAD

**Issue by natsukiai** [monkvision/monkjs#96]
Why not put the SIDEBAR_WIDTH in the style (and make `make_ratio` have it as a parameter)

The hardcoded 240 seems fishy :suspect:

_Originally posted by @rb46546741 in https://github.com/monkvision/monkjs/pull/92#discussion_r748342808_

**Comment by BenHakimIlyass** [comment]
Are we good with that in this [PR](https://github.com/monkvision/monkjs/pull/103/files)?
